name: CD - Despliegue Blue-Green

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t taller-pruebas-unitarias:${{ github.sha }} .

      - name: Dar permisos de ejecucion a los scripts
        run: chmod +x deploy/*.sh

      - name: Ejecutar despliegue Blue-Green
        run: bash deploy/deploy.sh taller-pruebas-unitarias:${{ github.sha }}